// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------ //
// BitsExpander //
// ------------ //

#define BitsExpander_wrap_target 0
#define BitsExpander_wrap 10

static const uint16_t BitsExpander_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block                      
    0x6021, //  1: out    x, 1                       
    0x0028, //  2: jmp    !x, 8                      
    0xe043, //  3: set    y, 3                       
    0xe02f, //  4: set    x, 15                      
    0x4024, //  5: in     x, 4                       
    0x0084, //  6: jmp    y--, 4                     
    0x0009, //  7: jmp    9                          
    0x4070, //  8: in     null, 16                   
    0xe020, //  9: set    x, 0                       
    0x00e1, // 10: jmp    !osre, 1                   
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program BitsExpander_program = {
    .instructions = BitsExpander_program_instructions,
    .length = 11,
    .origin = -1,
};

static inline pio_sm_config BitsExpander_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + BitsExpander_wrap_target, offset + BitsExpander_wrap);
    return c;
}
#endif

